### PR TITLE
make pinax-referrals work with Django 1.10+

### LINKED ISSUE #30: Django 1.10 middleware issue
When trying to install piano-referral on Django 1.10 I am getting the following errors:

`TypeError: object() takes no parameters`

Traveback:

```
application = get_wsgi_application()
  File "/path/to/my/env/env/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/path/to/my/env/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/path/to/my/env/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

### PR DESCRIPTION
**Pull request by nschlemm**
* added simple tests for creating and processing referrals
* fixes #30 through django.utils.deprecation.MiddlewareMixin for now
* avoid TypeError: render_to_string() got an unexpected keyword argument 'context_instance'
* adjusted tox.ini to currently supported python and django versions

### CODE REVIEW

**Comment by fcpauldiaz** [comment]
Why this pull request is not merged?

**Comment by paltman** [comment]
I had to manually merge it to resolve conflicts and github didn't seem to pick it up.  Thanks!
